// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRAwI3fzbjEutcIP_Mh_JwLM6LNDYLzY',
    appId: '1:220809017366:web:fcedf6a83c12a845b19d37',
    messagingSenderId: '220809017366',
    projectId: 'veinline-4d266',
    authDomain: 'veinline-4d266.firebaseapp.com',
    storageBucket: 'veinline-4d266.appspot.com',
    measurementId: 'G-DKB4EXPPDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Z5vA1y1VTT3R3AtnNMhDTgzkWbqjZn8',
    appId: '1:220809017366:android:a3365c4dedfbd2e9b19d37',
    messagingSenderId: '220809017366',
    projectId: 'veinline-4d266',
    storageBucket: 'veinline-4d266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJEoOg5CokUzQ93mPJUx__yxEkEsV4ioY',
    appId: '1:220809017366:ios:e4e95f16ab2d6ec3b19d37',
    messagingSenderId: '220809017366',
    projectId: 'veinline-4d266',
    storageBucket: 'veinline-4d266.appspot.com',
    androidClientId: '220809017366-4cgnmhag9grpgsfajgmsvbtp9oc375hp.apps.googleusercontent.com',
    iosClientId: '220809017366-jpiomnrsm4rqk4vd920fht758oftauao.apps.googleusercontent.com',
    iosBundleId: 'com.example.veinline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJEoOg5CokUzQ93mPJUx__yxEkEsV4ioY',
    appId: '1:220809017366:ios:e4e95f16ab2d6ec3b19d37',
    messagingSenderId: '220809017366',
    projectId: 'veinline-4d266',
    storageBucket: 'veinline-4d266.appspot.com',
    androidClientId: '220809017366-4cgnmhag9grpgsfajgmsvbtp9oc375hp.apps.googleusercontent.com',
    iosClientId: '220809017366-jpiomnrsm4rqk4vd920fht758oftauao.apps.googleusercontent.com',
    iosBundleId: 'com.example.veinline',
  );
}
